### PR TITLE
KH-18819: Add Dockerfile for Workiva Build

### PR DESCRIPTION
**Pull request by micahbeeman-wf**
Adding a Dockerfile for Workiva Build to meet requirements

@kennytrytek-wf @valchapman-wk

### CODE REVIEW

**Comment by aviary3-wk** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on HipChat: InfoSec Forum._

**Review by kennytrytek-wf — APPROVED** [review]
+1 ⛄️

**Review by valchapman-wk — APPROVED** [review]
QA +1

**Comment by valchapman-wk** [comment]
@Workiva/release-management-pp

**Pull request merged**
