### PR TITLE
KH-19311 Dart Format

### PR DESCRIPTION
**Pull request by robbecker-wf**
# Overview
This code was never formatted using dart format. As we update it to be dart 2 compatible we'll be making changes. This is a separate PR that only runs dart format to keep changes separate.

# Changes
No functional code changes. Only ran dart format.

# Testing
- [ ] CI passes

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/teams/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on HipChat: InfoSec Forum._

**Review by micahbeeman-wf — APPROVED** [review]
+1

**Comment by robbecker-wf** [comment]
@michaelyeager-wf can you get this one merged?

**Comment by michaelyeager-wf** [comment]
QA +1

**Comment by michaelyeager-wf** [comment]
@Workiva/release-management-pp

**Pull request merged**
